# Generated by Django 4.0.6 on 2022-07-27 09:43

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_job_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telephone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
    ]
