# Generated by Django 4.0.6 on 2022-07-27 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_user_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.user'),
        ),
        migrations.AlterField(
            model_name='job',
            name='jobid',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.CreateModel(
            name='JobDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mem_num', models.IntegerField(null=True)),
                ('cpu_core', models.IntegerField(null=True)),
                ('gpu_num', models.IntegerField(null=True)),
                ('image_type', models.CharField(max_length=50, null=True)),
                ('jobdetail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.job')),
            ],
        ),
    ]
