# Generated by Django 4.0.6 on 2022-08-01 16:06

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telephone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('image_type', models.CharField(max_length=50, null=True)),
                ('start_time', models.CharField(max_length=20)),
                ('end_time', models.CharField(max_length=20)),
                ('during_time', models.CharField(max_length=20)),
                ('predict_endtime', models.CharField(max_length=20)),
                ('loginport_ftp', models.CharField(max_length=15, null=True)),
                ('loginport_gui_webtop', models.IntegerField(null=True)),
                ('loginport_gui_webide', models.IntegerField(null=True)),
                ('loginport_ssh', models.IntegerField(null=True)),
                ('jobid', models.CharField(max_length=50, null=True, unique=True)),
                ('mem_num', models.IntegerField(null=True)),
                ('cpu_core', models.IntegerField(null=True)),
                ('gpu_num', models.IntegerField(null=True)),
                ('status_job', models.CharField(max_length=20)),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
    ]
